#!/bin/bash
# chkconfig: - 64 36
# description: Oracle auto start-stop script.
### BEGIN INIT INFO
# Provides:       oracle-listener
# Required-Start: $network 
# Required-Stop:
# X-UnitedLinux-Should-Start:
# X-UnitedLinux-Should-Stop:
# Default-Start:  3 5
# Default-Stop:
# Description:    Start oracle
### END INIT INFO
#
# Set ORA_OWNER to the user id of the owner of the 
# Oracle database in ORACLE_HOME.


# LANG="de_DE.UTF-8"
ORACLE_SID="NTX"
. /usr/local/etc/profile-oracle
ORA_OWNER=oracle
LSNTR_ALIAS=LISTENER

if [ ! -f $ORACLE_HOME/bin/lsnrctl ]
then
    echo "Oracle Listener startup: cannot start"
    exit
fi

case "$1" in
    start)
        # Start the Oracle databases:
        # The following command assumes that the oracle login 
        # will not prompt the user for any values
	su $ORA_OWNER -c "$ORACLE_HOME/bin/lsnrctl start"
        touch /var/lock/subsys/oracle-listener-$LSNTR_ALIAS
        ;;
    stop)
        # Stop the Oracle databases:
        # The following command assumes that the oracle login 
        # will not prompt the user for any values
	su $ORA_OWNER -c "$ORACLE_HOME/bin/lsnrctl stop"
        rm -f /var/lock/subsys/oracle-listener-$LSNTR_ALIAS
        ;;
    status)
	su $ORA_OWNER -c "$ORACLE_HOME/bin/lsnrctl status"
	;;
    restart)
	$0 stop
	$0 start
	;;
esac
